%define shortVersion %(echo %{version} | cut -d. -f1,2)

# Existing cooker cmake is uninstallable after the jsoncpp 1.9.8 soname
# bump (so.26 -> so.27). Bootstrap once so we can publish 4.4.2, then
# rebuild without bootstrap to restore system jsoncpp/cppdap and qtgui.
%bcond_without bootstrap

# Keep this in sync with the list of cross tools we build
# in other packages (binutils, gcc, ...)
%global targets aarch64-linux armv7hnl-linux i686-linux x86_64-linux x32-linux riscv32-linux riscv64-linux aarch64-linuxmusl armv7hnl-linuxmusl i686-linuxmusl x86_64-linuxmusl x32-linuxmusl riscv32-linuxmusl riscv64-linuxmusl aarch64-linuxuclibc armv7hnl-linuxuclibc i686-linuxuclibc x86_64-linuxuclibc x32-linuxuclibc riscv32-linuxuclibc riscv64-linuxuclibc aarch64-android armv7l-android armv8l-android x86_64-android i686-mingw32 x86_64-mingw32 ppc64le-linux ppc64le-linuxmusl ppc64le-linuxuclibc ppc64-linux ppc64-linuxmusl ppc64-linuxuclibc loongarch64-linux loongarch64-linuxmusl
%global long_targets %(
	for i in %{targets}; do
		CPU=$(echo $i |cut -d- -f1)
		OS=$(echo $i |cut -d- -f2)
		echo -n "$(rpm --target=${CPU}-${OS} -E %%{_target_platform}) "
	done
)

%if %{with bootstrap}
%bcond_with gui
%else
# The RISC-V port doesn't have Qt yet
%ifarch %{riscv}
%bcond_with gui
%else
%bcond_without gui
%endif
%endif

#define beta rc5

%ifarch %{arm}
# https://gitlab.kitware.com/cmake/cmake/-/issues/20568
%global optflags %{optflags} -D_FILE_OFFSET_BITS=64
%endif
%ifarch %{aarch64}
# On builders with a lot of cores but not a lot of memory,
# cmake builds tend to get killed by the OOM killer
%global optflags %{optflags} -g1
%endif

# Ignore dependencies generated by the cmake provider:
# They would pull in a slew of packages, including obsolete
# cruft that isn't even in the repos anymore like KDE4, because
# those cmake files are referenced in the sample Find*.cmake
# files shipped with cmake
%define __requires_exclude ^\\(?cmake\\(.*

Name:		cmake
Summary:	Cross-platform, open-source make system
Version:	4.4.2
Release:	%{?beta:0.%{beta}.}1
Source0:	http://www.cmake.org/files/v%{shortVersion}/%{name}-%{version}%{?beta:-%{beta}}.tar.gz
License:	BSD
Group:		Development/Other
Url:		https://www.cmake.org/HTML/index.html
Source1:	https://src.fedoraproject.org/rpms/cmake/raw/master/f/cmake.attr
# cmake.prov is based on Fedora's versions found at
# https://src.fedoraproject.org/rpms/cmake/raw/master/f/cmake.prov
# And fixed up to handle e.g. cmake(PkgConfig) correctly.
Source2:	cmake.prov
# cmake.req is based on Fedora's versions found at
# https://src.fedoraproject.org/rpms/cmake/raw/master/f/cmake.req
# And extended with a simplistic check for KDE Frameworks interdependencies
# Also, we drop the cmake-filesystem requirement (which is a non-issue in OM)
Source3:	cmake.req
Source100:	cmake.rpmlintrc
Patch0:		cmake-3.23.2-qt6-searchpath.patch
# cmake export files include an "integrity check" to make sure all related
# files are installed -- but it frequently does more harm than good, e.g.
# insisting all LLVM static libraries are installed when only the shared
# library is being used, or making sure all Qt style plugins are installed
# when QtGui is being used without needing any styles.
# Turn the fatal error into a warning.
Patch1:		cmake-3.24.0-dont-barf-on-integrity-check.patch
# Similar check for a missing directory referenced as include path
Patch2:		cmake-3.30.4-dont-barf-on-missing-directory.patch
Patch3:		cmake-3.4.1-dont-override-fPIC-with-fPIE.patch
# Don't throw a fatal error on
# cmake_minimum_required(VERSION something.before.3.5)
# This would currently break hundreds of packages
Patch4:		cmake-4.0.0-allow-old-cmake_minimum_required.patch
BuildRequires:	perl
BuildRequires:	pkgconfig(ncurses)
BuildRequires:	pkgconfig(zlib)
BuildRequires:	xz
BuildRequires:	pkgconfig(expat)
BuildRequires:	pkgconfig(bzip2)
BuildRequires:	pkgconfig(libssl)
BuildRequires:	python-sphinx
BuildRequires:	make
%if !%{with bootstrap}
# These -devel packages Require cmake() (via shipped *.cmake files). After
# the jsoncpp 1.9.8 soname bump, cooker cmake is uninstallable, so the
# bootstrap build must not pull them in.
BuildRequires:	pkgconfig(libcurl)
BuildRequires:	pkgconfig(libidn)
BuildRequires:	pkgconfig(libuv)
BuildRequires:	pkgconfig(libarchive)
# We need a copy of ourselves for the cmake(*) dependency generator to work
# and create all the cmake(*) Provides for the built-in modules
BuildRequires:	pkgconfig(libzstd)
BuildRequires:	cmake
BuildRequires:	cmake(jsoncpp)
BuildRequires:	cmake(cppdap)
BuildRequires:	rhash-devel
BuildRequires:	gcc-gfortran
%endif
%if %{with gui}
BuildRequires:	qmake-qt6
BuildRequires:	pkgconfig(Qt6Gui)
BuildRequires:	pkgconfig(Qt6Widgets)
%endif
# For compatibility with Fedora and Mageia
Provides:	cmake-filesystem = %{EVRD}
Provides:	cmake-filesystem%{?_isa} = %{EVRD}
%if %{with bootstrap}
# The cmake() RPM generator lives in the cmake package itself, so a
# bootstrap chroot cannot emit these. Mirror the Find-module provides
# from 4.4.1 so -devel packages that Require cmake(...) can install.
Provides:	cmake(ALSA)
Provides:	cmake(ASPELL)
Provides:	cmake(AVIFile)
Provides:	cmake(Armadillo)
Provides:	cmake(BISON)
Provides:	cmake(BLAS)
Provides:	cmake(BZip2)
Provides:	cmake(Backtrace)
Provides:	cmake(Boost)
Provides:	cmake(Bullet)
Provides:	cmake(CABLE)
Provides:	cmake(CUDA)
Provides:	cmake(CUDAToolkit)
Provides:	cmake(CURL)
Provides:	cmake(CVS)
Provides:	cmake(CheckFlagCommon)
Provides:	cmake(Coin3D)
Provides:	cmake(Cups)
Provides:	cmake(Curses)
Provides:	cmake(CxxTest)
Provides:	cmake(Cygwin)
Provides:	cmake(DCMTK)
Provides:	cmake(Dart)
Provides:	cmake(DevIL)
Provides:	cmake(Doxygen)
Provides:	cmake(EXPAT)
Provides:	cmake(EnvModules)
Provides:	cmake(FLEX)
Provides:	cmake(FLTK)
Provides:	cmake(FLTK2)
Provides:	cmake(Fontconfig)
Provides:	cmake(Freetype)
Provides:	cmake(GCCXML)
Provides:	cmake(GDAL)
Provides:	cmake(GIF)
Provides:	cmake(GLEW)
Provides:	cmake(GLU)
Provides:	cmake(GLUT)
Provides:	cmake(GSL)
Provides:	cmake(GTK)
Provides:	cmake(GTK2)
Provides:	cmake(GTest)
Provides:	cmake(Gettext)
Provides:	cmake(Git)
Provides:	cmake(GnuTLS)
Provides:	cmake(Gnuplot)
Provides:	cmake(HDF5)
Provides:	cmake(HSPELL)
Provides:	cmake(HTMLHelp)
Provides:	cmake(Hg)
Provides:	cmake(ICU)
Provides:	cmake(Ice)
Provides:	cmake(Iconv)
Provides:	cmake(Icotool)
Provides:	cmake(ImageMagick)
Provides:	cmake(Intl)
Provides:	cmake(JNI)
Provides:	cmake(JPEG)
Provides:	cmake(Jasper)
Provides:	cmake(Java)
Provides:	cmake(KDE3)
Provides:	cmake(KDE4)
Provides:	cmake(LAPACK)
Provides:	cmake(LATEX)
Provides:	cmake(LTTngUST)
Provides:	cmake(LibArchive)
Provides:	cmake(LibLZMA)
Provides:	cmake(LibXml2)
Provides:	cmake(LibXslt)
Provides:	cmake(Libinput)
Provides:	cmake(Lua)
Provides:	cmake(Lua50)
Provides:	cmake(Lua51)
Provides:	cmake(MFC)
Provides:	cmake(MPEG)
Provides:	cmake(MPEG2)
Provides:	cmake(MPI)
Provides:	cmake(Matlab)
Provides:	cmake(Motif)
Provides:	cmake(Msys)
Provides:	cmake(ODBC)
Provides:	cmake(OpenACC)
Provides:	cmake(OpenAL)
Provides:	cmake(OpenCL)
Provides:	cmake(OpenGL)
Provides:	cmake(OpenMP)
Provides:	cmake(OpenSP)
Provides:	cmake(OpenSSL)
Provides:	cmake(OpenSceneGraph)
Provides:	cmake(OpenThreads)
Provides:	cmake(PHP4)
Provides:	cmake(PNG)
Provides:	cmake(PackageHandleStandardArgs)
Provides:	cmake(PackageMessage)
Provides:	cmake(Patch)
Provides:	cmake(Perl)
Provides:	cmake(PerlLibs)
Provides:	cmake(PhysFS)
Provides:	cmake(Pike)
Provides:	cmake(PkgConfig)
Provides:	cmake(PostgreSQL)
Provides:	cmake(Producer)
Provides:	cmake(Protobuf)
Provides:	cmake(Python)
Provides:	cmake(Python2)
Provides:	cmake(Python3)
Provides:	cmake(PythonInterp)
Provides:	cmake(PythonLibs)
Provides:	cmake(Qt)
Provides:	cmake(Qt3)
Provides:	cmake(Qt4)
Provides:	cmake(QuickTime)
Provides:	cmake(RTI)
Provides:	cmake(Ruby)
Provides:	cmake(SDL)
Provides:	cmake(SDL_gfx)
Provides:	cmake(SDL_image)
Provides:	cmake(SDL_mixer)
Provides:	cmake(SDL_net)
Provides:	cmake(SDL_sound)
Provides:	cmake(SDL_ttf)
Provides:	cmake(SQLite3)
Provides:	cmake(SWIG)
Provides:	cmake(SelfPackers)
Provides:	cmake(Squish)
Provides:	cmake(Subversion)
Provides:	cmake(TCL)
Provides:	cmake(TIFF)
Provides:	cmake(TclStub)
Provides:	cmake(Tclsh)
Provides:	cmake(Threads)
Provides:	cmake(UnixCommands)
Provides:	cmake(UsePkg)
Provides:	cmake(Vulkan)
Provides:	cmake(Wget)
Provides:	cmake(Wish)
Provides:	cmake(X11)
Provides:	cmake(XCTest)
Provides:	cmake(XMLRPC)
Provides:	cmake(XalanC)
Provides:	cmake(XercesC)
Provides:	cmake(ZLIB)
Provides:	cmake(alsa)
Provides:	cmake(armadillo)
Provides:	cmake(aspell)
Provides:	cmake(avifile)
Provides:	cmake(backtrace)
Provides:	cmake(bison)
Provides:	cmake(blas)
Provides:	cmake(boost)
Provides:	cmake(bullet)
Provides:	cmake(bzip2)
Provides:	cmake(cable)
Provides:	cmake(checkflagcommon)
Provides:	cmake(coin3d)
Provides:	cmake(cuda)
Provides:	cmake(cudatoolkit)
Provides:	cmake(cups)
Provides:	cmake(curl)
Provides:	cmake(curses)
Provides:	cmake(cvs)
Provides:	cmake(cxxtest)
Provides:	cmake(cygwin)
Provides:	cmake(dart)
Provides:	cmake(dcmtk)
Provides:	cmake(devil)
Provides:	cmake(doxygen)
Provides:	cmake(envmodules)
Provides:	cmake(expat)
Provides:	cmake(flex)
Provides:	cmake(fltk)
Provides:	cmake(fltk2)
Provides:	cmake(fontconfig)
Provides:	cmake(freetype)
Provides:	cmake(gccxml)
Provides:	cmake(gdal)
Provides:	cmake(gettext)
Provides:	cmake(gif)
Provides:	cmake(git)
Provides:	cmake(glew)
Provides:	cmake(glu)
Provides:	cmake(glut)
Provides:	cmake(gnuplot)
Provides:	cmake(gnutls)
Provides:	cmake(gsl)
Provides:	cmake(gtest)
Provides:	cmake(gtk)
Provides:	cmake(gtk2)
Provides:	cmake(hdf5)
Provides:	cmake(hg)
Provides:	cmake(hspell)
Provides:	cmake(htmlhelp)
Provides:	cmake(ice)
Provides:	cmake(iconv)
Provides:	cmake(icotool)
Provides:	cmake(icu)
Provides:	cmake(imagemagick)
Provides:	cmake(intl)
Provides:	cmake(jasper)
Provides:	cmake(java)
Provides:	cmake(jni)
Provides:	cmake(jpeg)
Provides:	cmake(kde3)
Provides:	cmake(kde4)
Provides:	cmake(lapack)
Provides:	cmake(latex)
Provides:	cmake(libarchive)
Provides:	cmake(libinput)
Provides:	cmake(liblzma)
Provides:	cmake(libxml2)
Provides:	cmake(libxslt)
Provides:	cmake(lttngust)
Provides:	cmake(lua)
Provides:	cmake(lua50)
Provides:	cmake(lua51)
Provides:	cmake(matlab)
Provides:	cmake(mfc)
Provides:	cmake(motif)
Provides:	cmake(mpeg)
Provides:	cmake(mpeg2)
Provides:	cmake(mpi)
Provides:	cmake(msys)
Provides:	cmake(odbc)
Provides:	cmake(openacc)
Provides:	cmake(openal)
Provides:	cmake(opencl)
Provides:	cmake(opengl)
Provides:	cmake(openmp)
Provides:	cmake(openscenegraph)
Provides:	cmake(opensp)
Provides:	cmake(openssl)
Provides:	cmake(openthreads)
Provides:	cmake(osg)
Provides:	cmake(osgAnimation)
Provides:	cmake(osgDB)
Provides:	cmake(osgFX)
Provides:	cmake(osgGA)
Provides:	cmake(osgIntrospection)
Provides:	cmake(osgManipulator)
Provides:	cmake(osgParticle)
Provides:	cmake(osgPresentation)
Provides:	cmake(osgProducer)
Provides:	cmake(osgQt)
Provides:	cmake(osgShadow)
Provides:	cmake(osgSim)
Provides:	cmake(osgTerrain)
Provides:	cmake(osgText)
Provides:	cmake(osgUtil)
Provides:	cmake(osgViewer)
Provides:	cmake(osgVolume)
Provides:	cmake(osgWidget)
Provides:	cmake(osg_functions)
Provides:	cmake(osganimation)
Provides:	cmake(osgdb)
Provides:	cmake(osgfx)
Provides:	cmake(osgga)
Provides:	cmake(osgintrospection)
Provides:	cmake(osgmanipulator)
Provides:	cmake(osgparticle)
Provides:	cmake(osgpresentation)
Provides:	cmake(osgproducer)
Provides:	cmake(osgqt)
Provides:	cmake(osgshadow)
Provides:	cmake(osgsim)
Provides:	cmake(osgterrain)
Provides:	cmake(osgtext)
Provides:	cmake(osgutil)
Provides:	cmake(osgviewer)
Provides:	cmake(osgvolume)
Provides:	cmake(osgwidget)
Provides:	cmake(packagehandlestandardargs)
Provides:	cmake(packagemessage)
Provides:	cmake(patch)
Provides:	cmake(perl)
Provides:	cmake(perllibs)
Provides:	cmake(php4)
Provides:	cmake(physfs)
Provides:	cmake(pike)
Provides:	cmake(pkgconfig)
Provides:	cmake(png)
Provides:	cmake(postgresql)
Provides:	cmake(producer)
Provides:	cmake(protobuf)
Provides:	cmake(python)
Provides:	cmake(python2)
Provides:	cmake(python3)
Provides:	cmake(pythoninterp)
Provides:	cmake(pythonlibs)
Provides:	cmake(qt)
Provides:	cmake(qt3)
Provides:	cmake(qt4)
Provides:	cmake(quicktime)
Provides:	cmake(rti)
Provides:	cmake(ruby)
Provides:	cmake(sdl)
Provides:	cmake(sdl_gfx)
Provides:	cmake(sdl_image)
Provides:	cmake(sdl_mixer)
Provides:	cmake(sdl_net)
Provides:	cmake(sdl_sound)
Provides:	cmake(sdl_ttf)
Provides:	cmake(selfpackers)
Provides:	cmake(sqlite3)
Provides:	cmake(squish)
Provides:	cmake(subversion)
Provides:	cmake(swig)
Provides:	cmake(tcl)
Provides:	cmake(tclsh)
Provides:	cmake(tclstub)
Provides:	cmake(threads)
Provides:	cmake(tiff)
Provides:	cmake(unixcommands)
Provides:	cmake(usepkg)
Provides:	cmake(vulkan)
Provides:	cmake(wget)
Provides:	cmake(wish)
Provides:	cmake(wxWidgets)
Provides:	cmake(wxWindows)
Provides:	cmake(wxwidgets)
Provides:	cmake(wxwindows)
Provides:	cmake(x11)
Provides:	cmake(xalanc)
Provides:	cmake(xctest)
Provides:	cmake(xercesc)
Provides:	cmake(xmlrpc)
Provides:	cmake(zlib)
%endif
%ifarch %{arm}
Provides:	cmake-filesystem(armel-32) = %{EVRD}
%endif

%description
CMake is used to control the software compilation process using
simple platform and compiler independent configuration files.
CMake generates native makefiles and workspaces that can be
used in the compiler environment of your choice. CMake is quite
sophisticated: it is possible to support complex environments
requiring system configuration, pre-processor generation, code
generation, and template instantiation.

%files
%{_bindir}/cmake
%{_bindir}/ccmake
%{_bindir}/ctest
%{_bindir}/cpack
%{_datadir}/%{name}
%{_sysconfdir}/emacs/site-start.d/%{name}.el
%{_rpmconfigdir}/fileattrs/%{name}.attr
%{_rpmconfigdir}/%{name}.*
%{_datadir}/emacs/site-lisp/cmake-mode.el
%{_datadir}/vim/*/*
%{_datadir}/aclocal/cmake.m4
%{_datadir}/bash-completion/completions/*

%package doc
Summary:	Documentation for %{name}
Group:		Development/Other
BuildArch:	noarch
Conflicts:	%{name} < 3.5.2-3

%description doc
Documentation for %{name}.

%files doc
%if ! %{cross_compiling}
%doc mydocs/*
%endif
%doc %{_mandir}/man1/*.1.*
%doc %{_mandir}/man7/*.7.*

#-----------------------------------------------------------------------------

%if %{with gui}
%package -n	%{name}-qtgui
Summary:	Qt GUI Dialog for CMake - the Cross-platform, open-source make system
Group:		Development/Other
Requires:	%{name}
# (tpg) Fix for bug https://issues.openmandriva.org/show_bug.cgi?id=833
Requires:	%{_lib}qt5gui5
Requires:	%{_lib}xcb-util-renderutil0
Requires:	%{_lib}xcb-icccm4

%description -n	%{name}-qtgui
CMake is used to control the software compilation process using
simple platform and compiler independent configuration files.

This is the Qt GUI.

%files -n %{name}-qtgui
%{_bindir}/cmake-gui
%{_datadir}/applications/cmake-gui.desktop
%{_datadir}/mime/packages/cmakecache.xml
%{_datadir}/icons/*/*/*/CMakeSetup.png
%endif

#-----------------------------------------------------------------------------

%prep
%autosetup -n %{name}-%{version}%{?beta:-%{beta}} -p1

# Don't try to automagically find files in /usr/X11R6
# But also don't change a prefix if it is not /usr
perl -pi -e 's@^\s+/usr/X11R6/.*\n@@' Modules/*.cmake

# Find Qt 6 (cont. from Patch0)
sed -i -e 's,@QT6DIR@,%{_libdir}/qt6,g' Source/cmFindCommon.cxx

%ifarch %{arm}
# bootstrap test is taking ages on arm
sed -i -e 's!SET(CMAKE_LONG_TEST_TIMEOUT 1500)!SET(CMAKE_LONG_TEST_TIMEOUT 7200)!g' Tests/CMakeLists.txt
%endif

%if %{cross_compiling}
%cmake \
	-DCMAKE_DATA_DIR=share/cmake \
	-DCMAKE_MAN_DIR=share/man \
	-DCMAKE_DOC_DIR=share/doc/cmake \
	-DSPHINX_MAN=ON
%else
mkdir -p build
cd build
%set_build_flags
if ! ../configure \
	--system-libs \
	--prefix=%{_prefix} \
	--datadir=/share/%{name} \
	--mandir=/share/man \
	--docdir=/share/doc/%{name} \
%if %{with gui}
	--qt-gui \
	--qt-qmake=%{_libdir}/qt6/bin/qmake \
%endif
	--sphinx-man \
%if %{with bootstrap}
	--no-system-libs \
	--no-system-jsoncpp \
	--no-system-librhash \
%endif
	--parallel=%{_smp_mflags}; then
		cat Bootstrap.cmk/cmake_bootstrap.log
		exit 1
fi
%endif

%build
%make_build -C build

%install
%make_install -C build

# cmake mode for emacs
mkdir -p %{buildroot}%{_sysconfdir}/emacs/site-start.d
cat <<EOF >%{buildroot}%{_sysconfdir}/emacs/site-start.d/%{name}.el
(setq load-path (cons (expand-file-name "/dir/with/cmake-mode") load-path))
(require 'cmake-mode)
(setq auto-mode-alist
	  (append '(("CMakeLists\\\\.txt\\\\'" . cmake-mode)
				("\\\\.cmake\\\\'" . cmake-mode))
			  auto-mode-alist))
EOF

# Create toolchain files for supported and semi-supported
# crosscompilers...
mkdir -p %{buildroot}%{_datadir}/cmake/toolchains
for i in %{long_targets}; do
	SV=1
	if echo $i |grep -qi linux; then
		SYSTEM=Linux
	elif echo $i |grep -qi android; then
		SYSTEM=Android
	elif echo $i |grep -qi mingw; then
		SYSTEM=Windows
		SV=10.0
	else
		SYSTEM=$(echo ${i}|cut -d- -f3)
	fi
	ARCH=$(echo ${i}|cut -d- -f1)
	case $ARCH in
	arm*)
		ARCH=arm
		;;
	i?86|pentium?|athlon)
		ARCH=i386
		;;
	znver*|x86_64*)
		ARCH=x86_64
		;;
	esac

	cat >%{buildroot}%{_datadir}/cmake/toolchains/${i}.toolchain <<EOF
set(CMAKE_SYSTEM_NAME $SYSTEM)
set(CMAKE_SYSTEM_VERSION $SV)
set(CMAKE_SYSTEM_PROCESSOR $ARCH)

set(CMAKE_SYSROOT %{_prefix}/$i)

set(CMAKE_C_COMPILER %{_bindir}/clang)
set(CMAKE_C_COMPILER_TARGET $i)
set(CMAKE_CXX_COMPILER %{_bindir}/clang++)
set(CMAKE_CXX_COMPILER_TARGET $i)

set(CMAKE_FIND_ROOT_PATH %{_prefix}/$i)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
EOF
	cat >%{buildroot}%{_datadir}/cmake/toolchains/${i}-gcc.toolchain <<EOF
set(CMAKE_SYSTEM_NAME $SYSTEM)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR $ARCH)

set(CMAKE_SYSROOT %{_prefix}/$i)

set(CMAKE_C_COMPILER %{_bindir}/$i-gcc)
set(CMAKE_CXX_COMPILER %{_bindir}/$i-g++)

set(CMAKE_FIND_ROOT_PATH %{_prefix}/$i)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
EOF
done

# RPM dependency generators
install -m644 %{S:1} -D %{buildroot}%{_rpmconfigdir}/fileattrs/%{name}.attr
install -m755 %{S:2} -D %{buildroot}%{_rpmconfigdir}/%{name}.prov
install -m755 %{S:3} -D %{buildroot}%{_rpmconfigdir}/%{name}.req

# %doc wipes out files in doc dir, fixed in cooker svn for rpm package, though
# not submitted yet, so we'll just work around this by moving it for now..
%if ! %{cross_compiling}
rm -rf mydocs
mv %{buildroot}%{_datadir}/doc/%{name} mydocs
%else
rm -rf %{buildroot}%{_datadir}/doc/%{name}
%endif

# As of 3.26.4, the following are known to FAIL:
#        132 - CPackComponentsForAll-RPM-default (Failed)
#        133 - CPackComponentsForAll-RPM-OnePackPerGroup (Failed)
#        134 - CPackComponentsForAll-RPM-IgnoreGroup (Failed)
#        135 - CPackComponentsForAll-RPM-AllInOne (Failed)
#        428 - RunCMake.ParseImplicitLinkInfo (Failed)
#        486 - RunCMake.find_package (Failed)
#        583 - RunCMake.CPack_RPM.CUSTOM_NAMES (Failed)
#        584 - RunCMake.CPack_RPM.DEBUGINFO (Failed)
#        588 - RunCMake.CPack_RPM.EMPTY_DIR (Failed)
#        590 - RunCMake.CPack_RPM.INSTALL_SCRIPTS (Failed)
#        591 - RunCMake.CPack_RPM.MAIN_COMPONENT (Failed)
#        594 - RunCMake.CPack_RPM.PER_COMPONENT_FIELDS (Failed)
#        595 - RunCMake.CPack_RPM.SINGLE_DEBUGINFO (Failed)
#        596 - RunCMake.CPack_RPM.EXTRA_SLASH_IN_PATH (Failed)
%if 0
%check
unset DISPLAY
cd build
bin/ctest -E SubDirSpaces -V %{_smp_mflags}
%endif
